In [75]:
# 3D Heatmap in Python using matplotlib
  
# to make plot interactive 
%matplotlib
  
# importing required libraries
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
from pylab import *
from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
import matplotlib.colors

Using matplotlib backend: QtAgg


In [76]:
import matplotlib.pyplot as plt
import matplotlib as mpl

fig, ax = plt.subplots(figsize=(6, 1))
fig.subplots_adjust(bottom=0.5)

cmap = mpl.cm.RdYlGn
norm = mpl.colors.Normalize(vmin=0, vmax=20)

fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),
             cax=ax, orientation='horizontal', label='Capitalization Rate (%)')

In [77]:
# creating a dummy dataset
x_airbnb_price = np.random.randint(low=0, high=500, size=(300,))
y_zillow_price = np.random.randint(low=0, high=4000000, size=(300,))
z_occupency = np.random.randint(low=0, high=100, size=(300,))
z_occupency_decimal = z_occupency/100
occupency_days=np.round_(z_occupency_decimal*365,decimals = 0)
gross_income = [x_airbnb_price*occupency_days]
annual_costs=[12000]*300
net_operating_income=np.subtract(gross_income, annual_costs)
cap_rate_decimal = net_operating_income/y_zillow_price
cap_rate = cap_rate_decimal*100

# creating figures
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
  
# setting color bar
color_map = cm.ScalarMappable(cmap=cm.Greens_r)
color_map.set_array(cap_rate)

# creating the heatmap
img = ax.scatter(x_airbnb_price, y_zillow_price, z_occupency, marker='o',
                 s=150,color="green")
plt.colorbar(color_map)
  
# adding title and labels
ax.set_title("3D Heatmap")
ax.set_xlabel('Airbnb Price per Night')
ax.set_ylabel('Zillow House Price')
ax.set_zlabel('Occupency %')
  
# displaying plot
plt.show()

In [78]:
# creating a dummy dataset
x_airbnb_price = np.random.randint(low=0, high=500, size=(300,))
y_zillow_price = np.random.randint(low=0, high=4000000, size=(300,))
z_occupency = np.random.randint(low=0, high=100, size=(300,))
z_occupency_decimal = z_occupency/100
occupency_days=np.round_(z_occupency_decimal*365,decimals = 0)
gross_income = [x_airbnb_price*occupency_days]
annual_costs=[12000]*300
net_operating_income=np.subtract(gross_income, annual_costs)
cap_rate_decimal = net_operating_income/y_zillow_price
cap_rate = cap_rate_decimal*100


fig, ax = plt.subplots(figsize=(6, 1))
fig.subplots_adjust(bottom=0.5)

cmap = mpl.cm.RdYlGn
norm = mpl.colors.Normalize(vmin=0, vmax=20)

# fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),
#              cax=ax, orientation='horizontal', label='Capitalization Rate (%)')

# # creating figures
# fig = plt.figure(figsize=(10, 10))
# ax = fig.add_subplot(111, projection='3d')
  
# # setting color bar
# color_map = cm.ScalarMappable(cmap=cm.Greens_r)
# color_map.set_array(cap_rate)


# cmap = (mpl.colors.ListedColormap(['red', 'yellow', 'green'])
#         .with_extremes(over='0.25', under='0.75'))
# bounds = [0, 5, 15]
# norm = mpl.colors.BoundaryNorm(bounds, cmap.N)
# fig.colorbar(
#     mpl.cm.ScalarMappable(cmap=cmap, norm=norm),
#     cax=ax,
#     boundaries=[0] + bounds + [30],  # Adding values for extensions.
#     extend='both',
#     ticks=bounds,
#     spacing='proportional',
#     orientation='horizontal',
#     label='Discrete intervals, some other units',
# )



# creating the heatmap
img = ax.scatter(x_airbnb_price, y_zillow_price, z_occupency, marker='o',
                 cmap=cmap, norm=norm)
# plt.colorbar(color_map)
  
# adding title and labels
ax.set_title("3D Heatmap")
ax.set_xlabel('Airbnb Price per Night $')
ax.set_ylabel('Zillow House Price $')
ax.set_zlabel('Occupency %')
  
# displaying plot
plt.show()

AttributeError: 'AxesSubplot' object has no attribute 'set_zlabel'

In [ ]:
# creating a dummy dataset
x_airbnb_price = np.random.randint(low=0, high=500, size=(300,))
y_zillow_price = np.random.randint(low=0, high=4000000, size=(300,))
z_occupency = np.random.randint(low=0, high=100, size=(300,))
z_occupency_decimal = z_occupency/100
occupency_days=np.round_(z_occupency_decimal*365,decimals = 0)
gross_income = [x_airbnb_price*occupency_days]
annual_costs=[12000]*300
net_operating_income=np.subtract(gross_income, annual_costs)
cap_rate_decimal = net_operating_income/y_zillow_price
cap_rate = cap_rate_decimal*100


fig, ax = plt.subplots(figsize=(6, 1))
fig.subplots_adjust(bottom=0.5)

cmap = mpl.cm.RdYlGn
norm = mpl.colors.Normalize(vmin=0, vmax=20)

# fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),
             cax=ax, orientation='horizontal', label='Capitalization Rate (%)')

# creating the heatmap
plt.scatter(x_airbnb_price, y_zillow_price, z_occupency, marker='o')
img = plt.scatter(x_airbnb_price, y_zillow_price, z_occupency, marker='o')
# plt.colorbar(color_map)
  
# adding title and labels
ax.set_title("3D Heatmap")
ax.set_xlabel('Airbnb Price per Night')
ax.set_ylabel('Zillow House Price')
ax.set_zlabel('Occupency %')
  
# displaying plot
plt.show()

In [45]:
np.set_printoptions(suppress=True)
print(cap_rate)

[[  1.75403121  -0.31082371   6.36082346  -0.38726985   2.66293763
    0.98788476  -0.28330978   0.40034761  -0.12143965   0.25217298
    0.07757179  -0.27853794   1.1598793    5.44079034  -0.70306098
    0.85388713   2.41844909  -0.25190992   6.05119235   9.0893762
    0.90404685  -0.33920808   4.97135814   1.08521588   1.05692758
   -6.1589859    4.87020446   0.28766912  -1.93142394  12.56316844
   11.11883599   1.5799822   -4.15541207   0.29963951   0.88625383
    0.34708252   0.58114617   5.68538872   0.18546126   0.66759189
    1.06860343   8.39218389   2.98048628   1.45874288   1.89840377
    0.12808505   0.32896501   3.25270025   2.88569858   3.24389485
   -0.24484945  -0.21747808  -1.85325889   9.10619231  -0.33004049
    0.65688491  -0.14957501   1.0945007   -0.90826596  22.07918322
    5.32664556  -9.65686506  72.62074759  19.42037264   4.65270212
    0.49802121   3.04081353   6.36813235   0.93949427   1.35637191
    0.59131072  -0.63566001   4.03447011   0.34489921   2.38931

In [3]:
import matplotlib.pyplot as plt

plt.figure()
plt.ion()
ax1 = plt.subplot(211) #Here it freezes
plt.title('test', fontsize=8)
plt.xlim(-1700, 1700)
plt.ylabel('x-axis')
plt.xlabel('y-axis')
plt.grid()
plt.draw() # draw the plot
plt.pause(5) # show it for 5 seconds
print("Hallo") # continue doing other stuff

Hallo


In [28]:
z_occupency_decimal_percent

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
x_airbnb_price

array([309,  37, 271, 106, 255, 246, 144,  58, 184, 444, 469,  76,  35,
       309, 288, 180, 405, 438, 176, 247, 232,  82, 396, 226, 471, 419,
        39, 416, 250, 199, 486, 209, 467, 365,  11, 128, 344, 139, 234,
       437, 112, 388, 329, 499, 253, 149, 317, 495, 470, 457, 274,  71,
        25, 278, 233, 356, 211, 421, 360, 280, 474, 296, 213, 151, 438,
       298, 297, 292, 275, 339, 460, 371, 314,  16,  17, 219, 185, 165,
       227, 107, 494, 138, 366, 330, 347,  15, 298, 161, 404, 457,  78,
       302, 173,  79, 273, 348, 259,  75, 373, 443, 354, 368, 404, 315,
        24,  25, 289, 203, 101, 469, 407, 188, 403,  10, 372, 215,  21,
       294, 287, 270, 402, 445, 311,  59, 122, 147, 112,  92, 476, 221,
       156, 208, 219, 499,  63, 303, 448,  94, 146, 225,  72, 225, 266,
       339, 247, 445, 332, 445,  71, 293, 377, 265, 110, 263, 404, 302,
       409, 117, 155, 441, 194, 249, 132,  66, 203, 213,  95, 476, 398,
       123,  95, 166, 219, 476, 128, 323, 493, 375, 481, 498, 28

In [15]:
y_zillow_price

array([ 934410, 1231268, 1443558,  803842, 2438143, 1238128, 1439452,
        637799, 1876800, 2843548,  963341, 1863478, 2298556, 3729588,
       1247216, 3737176, 3930615,  505800, 2360140, 3895864,   47867,
        169988, 3352759,  702956, 3006270, 3956860,  987215, 2075372,
       2108639, 3769802, 1785813, 3157942, 2494993, 1853818, 1841361,
       1788551,  366479, 1164184, 2391919, 3938379, 3886103,  454495,
       1689886, 1998218, 2750019, 2964567, 3573159, 3696159, 1125173,
       1037456, 2077770, 2832098, 2730271,  363188, 2082225, 1734689,
       2142689, 3856883, 1790897, 2560920, 1111109,   58904, 2933495,
       3555848, 1510180, 3889494, 2623936,  710259, 2804558,  730020,
       3293065,  805465, 2312069, 3869796, 1425298, 2322244, 3434624,
       3576308, 1246054,  988807,  798023, 3695759, 2019739, 1900038,
       3916170, 2793544,  863993,  852057, 2631155,  452775, 3742192,
       1348903, 2819079, 2050255, 1451548, 3603370,  202622,  701126,
       1255322, 2101

In [16]:
z_occupency_decimal_percent

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.set_printoptions(suppress=True)
print(cap_rate)

[array([[ -0.35776485,   8.08128263,   0.18991666,   2.47214513,
          1.19125951,   3.49116612,   0.05569392,   8.03562741,
          1.64954496,   0.79781294,   1.25024289,   2.53019285,
          4.64674813,   1.84904253,   3.00395276,  -0.80509099,
         -0.47626015,   3.77527522,   0.66268016,  -0.11330764,
         -0.15481035,  -2.85200319,   0.02073035,   1.1075877 ,
          1.91392035,   0.20637704,   9.04614008,  -0.66419483,
          2.10809797,   0.67858854,   5.20461395,   3.18299422,
          1.15878877,  -0.38651615,   0.21160837,   4.17453812,
         16.94578167,   0.58856162,  23.66603305,   0.83232856,
          3.40225749,   8.27051759,   2.23730571,  -0.23465495,
          2.78299012,  -0.15505251,   0.40125353,  -0.38595705,
          0.11018936,   0.99818752,   5.10175009,   8.44673474,
          2.33583013,   0.61350156,   1.16533494,  14.70378686,
          0.9612798 ,   1.89825365,  -0.16897385,   5.08893094,
         12.70203254,  18.84827786,   7

In [12]:
gross_income

[array([1.4861e+02, 4.2770e+01, 8.1280e+01, 7.2240e+01, 6.5000e+00,
        2.7508e+02, 4.9000e-01, 4.0139e+02, 4.9000e+00, 3.5200e+02,
        4.1580e+01, 1.7028e+02, 1.2180e+02, 1.4145e+02, 3.3189e+02,
        0.0000e+00, 3.4132e+02, 1.2714e+02, 2.0444e+02, 8.6140e+01,
        1.6515e+02, 5.8050e+01, 2.3715e+02, 1.6185e+02, 2.8600e+01,
        9.9960e+01, 1.5776e+02, 1.0266e+02, 6.7340e+01, 3.0107e+02,
        2.8836e+02, 3.8880e+01, 1.7820e+02, 3.9820e+01, 2.2776e+02,
        2.7060e+01, 1.5688e+02, 1.4040e+01, 3.0080e+01, 1.3440e+02,
        8.2500e+01, 2.0511e+02, 1.2050e+02, 9.2480e+01, 5.5800e+01,
        2.0700e+02, 1.7138e+02, 1.5296e+02, 1.3243e+02, 1.3671e+02,
        4.1500e+01, 1.8640e+01, 2.8210e+02, 6.0160e+01, 2.5200e+01,
        2.8320e+01, 7.0800e+01, 1.4620e+01, 5.5290e+01, 1.0860e+01,
        4.4070e+01, 2.9694e+02, 9.3620e+01, 9.9000e+01, 1.7520e+01,
        9.9630e+01, 1.3860e+02, 1.2948e+02, 5.9840e+01, 5.7400e+01,
        2.5500e+01, 3.5672e+02, 2.5813e+02, 2.24

In [17]:
annual_costs

[12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,
 12000,


In [54]:
fig, ax = plt.subplots(figsize=(6, 1))
fig.subplots_adjust(bottom=0.5)

cmap = (mpl.colors.ListedColormap(['red',"f97306" ,'yellow','AAFF32', 'green'])
        .with_extremes(over='0.25', under='0.75'))

bounds = [-10, 0, 5, 12, 15, 20]
norm = mpl.colors.BoundaryNorm(bounds, cmap.N)
fig.colorbar(
    mpl.cm.ScalarMappable(cmap=cmap, norm=norm),
    cax=ax,
    boundaries=[0] + bounds + [13],  # Adding values for extensions.
    extend='both',
    ticks=bounds,
    spacing='proportional',
    orientation='horizontal',
    label='Discrete intervals, some other units',
)

ValueError: Invalid RGBA argument: 'f97306'

In [47]:
cmaps = {}

gradient = np.linspace(0, 1, 256)
gradient = np.vstack((gradient, gradient))


def plot_color_gradients(category, cmap_list):
    # Create figure and adjust figure height to number of colormaps
    nrows = len(cmap_list)
    figh = 0.35 + 0.15 + (nrows + (nrows - 1) * 0.1) * 0.22
    fig, axs = plt.subplots(nrows=nrows + 1, figsize=(6.4, figh))
    fig.subplots_adjust(top=1 - 0.35 / figh, bottom=0.15 / figh,
                        left=0.2, right=0.99)
    axs[0].set_title(f'{category} colormaps', fontsize=14)

    for ax, name in zip(axs, cmap_list):
        ax.imshow(gradient, aspect='auto', cmap=plt.get_cmap(name))
        ax.text(-0.01, 0.5, name, va='center', ha='right', fontsize=10,
                transform=ax.transAxes)

    # Turn off *all* ticks & spines, not just the ones with colormaps.
    for ax in axs:
        ax.set_axis_off()

    # Save colormap list for later.
    cmaps[category] = cmap_list

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
import matplotlib.colors
xdata=x_airbnb_price
ydata=y_zillow_price
norm=plt.Normalize(1,150)
colorlist=["darkorange", "gold", "lawngreen", "lightseagreen"]
newcmp = LinearSegmentedColormap.from_list('testCmap', colors=colorlist, N=256)
c=np.linspace(0,80,12)
plt.scatter(xdata,ydata,c=c, cmap=newcmp, norm=norm)
plt.colorbar()
plt.show()